---
- name: test if swap_swappiness_value is set correctly
  assert:
    that:
      - swap_swappiness_value is defined
      - swap_swappiness_value is number
      - swap_swappiness_value <= 100
      - swap_swappiness_value >= 0
    fail_msg: "'swap_swappiness_value' must be between 0 and 100"
    quiet: true
  when: swap_configure | bool

- name: test if packages_autoupdate_days_period is set correctly
  assert:
    that:
      - packages_autoupdate_days_period is defined
      - packages_autoupdate_days_period is number
    fail_msg: "'packages_autoupdate_days_period' must be number"
    quiet: true
  when: packages_autoupdate_enabled | bool
