---
- include_tasks: packages-RedHat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: packages-Debian.yml
  when: ansible_os_family == "Debian"

- name: Remove unnecessary packages
  package:
    state: absent
    name: "{{ packages_unnecessary_list | default(omit, true) }}"
  register: _progress_status
  until: _progress_status is succeeded
  delay: 5
  retries: 5

- name: Install required list of packages
  package:
    state: present
    name:
      - sudo
      - bash
      - iptables
      - openssl
      - curl
      - ca-certificates
      - gnupg
      - gnupg2
      - chrony
      - file
      - wget
      - libuser
      - net-tools
      - screen
      - tcpdump
      - sysstat
      - mlocate
      - telnet
      - bmon
      - htop
      - rkhunter
      - "{{ item }}"
  loop: "{{ packages_required_list | default(omit, true) }}"
  register: _progress_status
  until: _progress_status is succeeded
  delay: 5
  retries: 5

- name: Install extra list of packages
  package:
    state: present
    name:
      - nano
      - lnav
      - zip
      - unzip
      - at
      - git
      - nmap
  register: _progress_status
  until: _progress_status is succeeded
  delay: 5
  retries: 5
  when: packages_extra | bool
