---
- name: Ensure config file exists
  template:
    src: "ssh-config.j2"
    dest: "{{ ssh_config_path }}"
    owner: root
    group: root
    mode: "0600"
    validate: "sshd -T -C user=root -C host=localhost -C addr=localhost -C lport={{ ssh_port }} -f %s"
  notify: restart_sshd
