---
- name: Check if swap file exists
  stat:
    path: "{{ swap_file_path }}"
  register: _swap_file_check

- name: Remove old swap file
  block:
    - name: Turn off swap
      shell: "swapoff -a"
      args:
        executable: /bin/bash
      changed_when: false

    - name: Ensure swap file is absent
      file:
        path: "{{ swap_file_path }}"
        state: absent
      changed_when: false
  when: _swap_file_check.stat.exists

- name: Create swap file
  shell: "dd if=/dev/zero of={{ swap_file_path }} count='{{ swap_size }}' bs=1MiB"
  args:
    executable: /bin/bash
    creates: "{{ swap_file_path }}"
  changed_when: false

- name: Protect swap file
  file:
    path: "{{ swap_file_path }}"
    owner: "root"
    group: "root"
    mode: "0600"

- name: Format swap file
  shell: "mkswap {{ swap_file_path }}"
  args:
    executable: /bin/bash
  changed_when: false

- name: Write swap entry in fstab
  ansible.posix.mount:
    path: "swap"
    src: "{{ swap_file_path }}"
    fstype: "swap"
    opts: "sw"
    passno: 0
    dump: 0
    state: present

- name: Turn on swap
  shell: "swapon -a"
  args:
    executable: /bin/bash
  changed_when: false
