---
# This task configures sudo to prompt users for the root password
# instead of their own when executing commands with elevated privileges.
# This enhances security by restricting sudo access to those who know the root password.
- name: Restrict sudo access to root password
  lineinfile:
    path: "/etc/sudoers"
    regexp: "^rootpw"
    line: "Defaults rootpw"
    validate: "visudo -cf %s"

- name: Change timezone
  community.general.timezone:
    name: "{{ system_timezone }}"

- name: Add /etc/timezone file
  copy:
    content: "{{ system_timezone }}"
    dest: "/etc/timezone"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Ensure required locale exists
  community.general.locale_gen:
    name: "{{ system_locale }}"
    state: present
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version in ["10", "11"]

- name: Ensure systemd-logind service is in the right state
  systemd:
    name: systemd-logind
    state: started

- name: Set locale
  shell: "localectl set-locale LANG={{ system_locale }}"
  args:
    executable: /bin/bash
  changed_when: false

- name: Check if portable GNU assembler exist
  stat:
    path: "/usr/bin/as"
  register: _assembler_bin_check

- name: Protect portable GNU assembler
  file:
    path: "/usr/bin/as"
    owner: "root"
    group: "root"
    mode: "0750"
  when: _assembler_bin_check.stat.exists

- name: Gather the package facts
  package_facts:
    manager: auto

- name: Restrict access to at
  copy:
    content: "root"
    dest: "/etc/at.allow"
    owner: "root"
    group: "root"
    mode: "0600"
  when: "'at' in ansible_facts.packages"

- name: Protect at.deny file
  file:
    path: "/etc/at.deny"
    owner: "root"
    group: "root"
    mode: "0600"
  when: "'at' in ansible_facts.packages"
