---
- name: restart_sshd
  systemd:
    name: sshd
    state: restarted

- name: restart_unattended_upgrades
  systemd:
    name: unattended-upgrades
    state: restarted

- name: restart_auditd
  command:
    cmd: "service auditd restart" # rhel: see: https://access.redhat.com/solutions/2664811

- name: save_iptables_ipv4_rules
  community.general.iptables_state:
    ip_version: "ipv4"
    state: saved
    path: "/etc/sysconfig/iptables"
  listen: save_iptables_rules
  when: ansible_os_family == "RedHat"

- name: save_iptables_ipv6_rules
  community.general.iptables_state:
    ip_version: "ipv6"
    state: saved
    path: "/etc/sysconfig/ip6tables"
  listen: save_iptables_rules
  when: ansible_os_family == "RedHat"

- name: save_iptables_ipv4_rules
  community.general.iptables_state:
    ip_version: "ipv4"
    state: saved
    path: "/etc/iptables/rules.v4"
  listen: save_iptables_rules
  when: ansible_os_family == "Debian"

- name: save_iptables_ipv6_rules
  community.general.iptables_state:
    ip_version: "ipv6"
    state: saved
    path: "/etc/iptables/rules.v6"
  listen: save_iptables_rules
  when: ansible_os_family == "Debian"
