---
- name: Converge
  hosts: all
  become: true
  tasks:
    - include_role:
        name: "{{ lookup('env', 'ROLE_NAME') | default('ansible-role-linux', true) }}"
      vars:
        swap_configure: false
        packages_upgrade_all: false
        packages_extra: false
        system_root_user_password: "Test-Pa$$w0rd123456"
