name: CI
on:
  workflow_dispatch:
    inputs:
      runKics:
        description: Run KICS scan
        type: boolean
        default: false
  push:
    paths-ignore:
      - README.md
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]
  schedule:
    - cron: "15 3 * * 0"

env:
  ACTIONS_REPOSITORY: "gha-templates"

jobs:
  scan:
    name: Checkmarx KICS
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: inputs.runKics == true || github.event_name == 'push'
    permissions:
      contents: read # for actions/checkout to fetch code
      issues: write # for checkmarx/kics-github-action to write feedback to github issues
      pull-requests: write # for checkmarx/kics-github-action to write feedback to PR
      security-events: write # for github/codeql-action/upload-sarif to upload report for CodeQL/Security Alerts
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout actions repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ env.ACTIONS_REPOSITORY }}
          token: ${{ secrets.GHA_TOKEN }}
          path: gha_templates
          fetch-depth: 0

      - name: Run KICS scan
        uses: ./gha_templates/checkmarx-kics
        with:
          path: "tasks"
          uploadReport: true
